config/routes.rb
Rails.application.routes.draw do

resources :dreams, :dreamers

root "dreams#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dream.rb
class Dream < ApplicationRecord
  belongs_to :dreamer
end

app/models/dreamer.rb
class Dreamer < ApplicationRecord
  has_many :dreams
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dreamers_controller.rb
class DreamersController < ApplicationController
  def new
  end

  def edit
  end

  def index
  end

  def show
  end
end

app/controllers/dreams_controller.rb
class DreamsController < ApplicationController
  def new
    @dream = Dream.new
  end

  def create
    @dream = Dream.new(dream_params)
    if @dream.save
      redirect_to root_path, notice: "Dream Added"
    else
      render :new
    end
  end

  def index
    @dreams = Dream.all
  end

  def edit
    @dream = Dream.find_by id:  params[:id]
  end

  def show
    @dream = Dream.find_by id:  params[:id]
  end

  def update
    @dream = Dream.find_by id:  params[:id]
    if @dream.update(dream_params)
      redirect_to root_path, notice: "Dream Updated"
    else
      render :edit
    end
  end


  def dream_params
    params.require(:dream).permit(:title, :body, :dreamer_id, :dreamer)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dreamers_helper.rb
module DreamersHelper
end

app/helpers/dreams_helper.rb
module DreamsHelper
end

app/views/dreamers/edit.html.erb
<h1>Dreamers#edit</h1>
<p>Find me in app/views/dreamers/edit.html.erb</p>

app/views/dreamers/index.html.erb
<h1>Dreamers#index</h1>
<p>Find me in app/views/dreamers/index.html.erb</p>

app/views/dreamers/new.html.erb
<h1>Dreamers#new</h1>
<p>Find me in app/views/dreamers/new.html.erb</p>

app/views/dreamers/show.html.erb
<h1>Dreamers#show</h1>
<p>Find me in app/views/dreamers/show.html.erb</p>

app/views/dreams/_form.html.erb
<%= simple_form_for @dream do |f|%>
  <%= f.association :dreamer%>
  <%= f.input :title%>
  <%= f.input :body %>
  <%= f.button :submit%>
<%end%>

app/views/dreams/edit.html.erb
<h1>Alter Dream</h1>
<%= render 'form'%>

app/views/dreams/index.html.erb
<h1> Dreams </h1>
<ul>
    <% @dreams.each do |dream|%>
      <li><h3><%= link_to dream.title, dream_path(dream)%></h3></li>
    <%end%>
</ul> 

<h2><%= link_to "Keep Dreaming", new_dream_path %>
</h2>

app/views/dreams/new.html.erb
<h1>Dream a New Dream</h1>
<%= render 'form'%>

app/views/dreams/show.html.erb
<h1><%= @dream.title%></h1></hr>
<p><%= @dream.body%></p>
<p>by <%= @dream.dreamer.name%></p>
<p> <%= link_to "Update Dream", edit_dream_path(@dream)%></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DreamMachine</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>